name: CI

on:
  push:
    branches:
      - master

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install dependencies
        # The normal requirements.txt is installed as it provides files for mypy to use.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Pylint
        run: bash ./scripts/pylint_ci

      - name: Flake8
        run: flake8 ./spacexlaunchbot

      - name: MyPy
        run: mypy ./spacexlaunchbot

      - name: Bandit
        run: bandit -r ./spacexlaunchbot

      - name: Tests
        run: pytest

      - name: Build Docker image
        run: docker build -t psidex/spacexlaunchbot .

      - name: Push Docker image
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push psidex/spacexlaunchbot
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
